USE HowKTeam
GO

SELECT * FROM KHOA AS K
WHERE ( SELECT COUNT(*) FROM BOMON AS BM, GIAOVIEN AS GV
		WHERE BM.MABM = GV.MABM AND K.MAKHOA = BM.MAKHOA) >= 2


SELECT TENBM, PHONG, COUNT(*) AS N'Số lượng' FROM BOMON AS BM, GIAOVIEN AS GV
WHERE BM.MABM = GV.MABM
GROUP BY BM.TENBM, BM.PHONG
-- Lấy ra tên bộ môn và số lượng giáo viên dạy bộ môn đó
SELECT TENBM, PHONG, COUNT(*) AS N'Số lượng' FROM BOMON AS BM, GIAOVIEN AS GV
WHERE BM.MABM = GV.MABM
GROUP BY BM.PHONG, BM.TENBM

SELECT * FROM BOMON AS BM, GIAOVIEN AS GV
WHERE BM.MABM = GV.MABM
-- lấy ra danh sách lương giáo viên có lương > 50% lương trung bình của Giáo Viên
SELECT * FROM GIAOVIEN
WHERE LUONG > (SELECT AVG(LUONG) FROM GIAOVIEN)

SELECT * FROM GIAOVIEN
WHERE LUONG > (SELECT SUM(LUONG) FROM GIAOVIEN)/(SELECT COUNT(LUONG) FROM GIAOVIEN)

SELECT AVG(LUONG) AS N'Lương TB' FROM GIAOVIEN

SELECT * FROM DETAI
SELECT * FROM THAMGIADT

-- lấy ra tên giáo viên và số lượng đề tài giáo viên đó tham gia
SELECT  GV.MAGV,GV.HOTEN, COUNT(*)  FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN, GV.MAGV
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, THAMGIADT.MADT FROM GIAOVIEN, THAMGIADT

/*
Bài Tập:
1. Xuất ra tên giáo viên và số lượng người thân của giáo viên đó
SELECT GV.MAGV, GV.HOTEN, COUNT(*) AS N'Số lượng người thân' FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV
GROUP BY GV.MAGV,GV.HOTEN


SELECT GiAOVIEN.MAGV,GIAOVIEN.HOTEN, NGUOITHAN.TEN FROM GIAOVIEN, NGUOITHAN
WHERE GIAOVIEN.MAGV = NGUOITHAN.MAGV

2. Xuất ra tên giáo viên và số lượng đề tài giáo viên đó đã hoàn thành
SELECT GV.HOTEN, COUNT(*) AS N'Số lượng đề tài hoàn thành' FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT AND DT.NGAYKT <= GETDATE()
GROUP BY GV.HOTEN, GV.MAGV


SELECT GV.MAGV,GV.HOTEN, DT.MADT, DT.TENDT, DT.NGAYBD, DT.NGAYKT FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT AND DT.NGAYKT <= GETDATE()
ORDER BY HOTEN

3. Lấy ra tên khoa có tổng số lương của giáo viên là lớn nhất
SELECT TOP 1 K.TENKHOA, SUM(LUONG) AS N'Tổng lương' FROM GIAOVIEN AS GV, KHOA AS K, BOMON AS BM
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA 
GROUP BY K.TENKHOA
ORDER BY SUM(LUONG) DESC
*/



---------------------------------
-- GROUP BY - HAVING: having là where của group by
-- xuất ra số lượng giáo viên trong từng bộ môn mà số giáo viên >= 2
SELECT BM.MABM, BM.TENBM, COUNT(*) AS N'Số lượng giáo viên' FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(*) >= 2

-- Xuất ra mức lương và tổng tuổi của giáo viên nhận lương đó
SELECT LUONG, SUM(YEAR(GETDATE()) - YEAR(NGSINH)) AS N'Tổng tuổi' FROM GIAOVIEN
GROUP BY LUONG

-- Xuất ra mức lương và tổng tuổi của giáo viên nhận lương đó và có người thân
-- cách 1:
SELECT GV.LUONG, SUM(YEAR(GETDATE()) - YEAR(GV.NGSINH)) AS N'Tổng tuổi' FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV
GROUP BY GV.LUONG
-- cách 2
SELECT GV.LUONG, SUM(YEAR(GETDATE()) - YEAR(GV.NGSINH)) AS N'Tổng tuổi' FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV AND GV.MAGV IN (SELECT MAGV FROM NGUOITHAN)
GROUP BY GV.LUONG


-- Xuất ra mức lương và tổng tuổi của giáo viên nhận lương đó và có người thân and tuổi bé hơn tuổi trung bình
SELECT GV.LUONG, SUM(YEAR(GETDATE()) - YEAR(GV.NGSINH)) AS N'Tổng tuổi' FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV 
GROUP BY GV.LUONG, GV.NGSINH
HAVING (YEAR(GETDATE()) - YEAR(GV.NGSINH)) <
(
	SELECT AVG(YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH)) FROM GIAOVIEN
)